### ISSUE TITLE
Release for 1.1.1

### ISSUE THREAD

**Issue by stevie-mayhew** [richardsjoqvist/silverstripe-embedder#2]
Hey @richardsjoqvist,

Would you be able to tag a release containing @camspiers updates to support https? Just came up against this issue ourselves and I don't like tagging dev-master as the required version :smile: 

Cheers,
Stevie

**Comment by stevie-mayhew** [comment]
There are actually a couple of issues serving content from youtube over a HTTPS site, I'll do up a PR for the changes needed to allow it.

**Comment by richardsjoqvist** [comment]
Thanks man!
