### ISSUE TITLE
Project take over

### ISSUE THREAD

**Issue by sasky** [richardsjoqvist/silverstripe-embedder#7]
Hello.
If you like, I would be keen to take over this project and become the primary maintainer. 
That would basically include. 
- Creating phpunit, Travis and Scrutinizer tests.
- Puplishing on Packagist and addons.silverstripe.org.
- Adding more features as needed.

You said you are not working in Silverstripe any more? And I'm keen just to maintain a handy SS module.

Cheers
Cam

**Comment by richardsjoqvist** [comment]
Sure, you are welcome to take over the project. Glad to hear someone still finds a use for this :)

**Comment by richardsjoqvist** [comment]
Apparently you already have a fork of this project which prevents me from transferring it to you.

**Comment by sasky** [comment]
Cool thanks. I just deleted my fork.

**Comment by richardsjoqvist** [comment]
Alright, transfer request sent.
